### ISSUE TITLE
Edit Claims before update Django User Model

### ISSUE THREAD

**Issue by Pedro-Souto** [snok/django-auth-adfs#176]
Hi!

I'm logging user using afds but I wanted to include MSFT groups.
`"CLAIM_MAPPING": {"first_name": "Display Name", "groups": "group"},`

 How can I avoid this TypeError? 
> Direct assignment to the forward side of a many-to-many set is prohibited. Use groups.set() instead.

**Comment by JonasKs** [comment]
Huh? The `key` is the user model, the `value` represent what's in the actual token (claims)

It's hard to help without full log and a way to reproduce.

See [docs](https://django-auth-adfs.readthedocs.io/en/latest/troubleshooting.html#troubleshooting).

**Comment by Pedro-Souto** [comment]
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/oauth2/callback?code=AAAAAAAAAAAAAAAAAAAAAA.DxHxVO5i2QhjAIYkrasoBmD9lr8.SUSBfXG3L6AUku6cX3t70HT1AefS6Zr43U4dMGtdhLva01oRt_286z5HRWKC1eKWkKJEHBcz3eQ3G5S4yjuNyH4JrWiclkhO-uPsTMiPEAsf6DWch6EDspY2a2Wn5uVqVg9EgBVTrusDlslkni8vuD45yKr1S1GPpGQxRm3TuNTuA_xDCjmK8unv-ZCcOM4OmEWMi-35c_RLLl2Sc3kMcBI87KHLIR-CA-7vd60TZeHFbSG5i5HiaeZigIQaj3T9tYnNyJFi5FQb4Vb5YckJ3CuEQJ3QxJdprj61F8G4d8_1I3iNjUCENP9wzYbnHtIypjCWO4ZPekqXVQKym6cgsA&amp;state=Lw==

Django Version: 3.2.4
Python Version: 3.7.3
Installed Applications:
['dashboards.apps.DashboardsConfig',
 'middleOffice.apps.MiddleofficeConfig',
 'sei.apps.SeiConfig',
 'homepage.apps.HomepageConfig',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django_auth_adfs']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django_auth_adfs.middleware.LoginRequiredMiddleware']



Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django_auth_adfs\views.py", line 36, in get
    user = authenticate(request=request, authorization_code=code)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\decorators\debug.py", line 42, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\contrib\auth\__init__.py", line 76, in authenticate
    user = backend.authenticate(request, **credentials)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django_auth_adfs\backend.py", line 277, in authenticate
    user = self.process_access_token(access_token, adfs_response)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django_auth_adfs\backend.py", line 104, in process_access_token
    self.update_user_attributes(user, claims)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django_auth_adfs\backend.py", line 165, in update_user_attributes
    setattr(user, field, claims[claim])
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\db\models\fields\related_descriptors.py", line 547, in __set__
    % self._get_set_deprecation_msg_params(),

Exception Type: TypeError at /oauth2/callback
Exception Value: Direct assignment to the forward side of a many-to-many set is prohibited. Use groups.set() instead.

**Comment by JonasKs** [comment]
> It's hard to help without full log **and a way to reproduce.**

Do you use a custom user model? Sounds like the issue is there. If not, what's your settings?
