### ISSUE TITLE
TemplateDoesNotExist at /oauth2/callback

### ISSUE THREAD

**Issue by cataclysm1987** [snok/django-auth-adfs#185]
I am getting this error after sending the user to log in with AD and then sending it back to the app. 

I have set up the @login_required attribute on the index function in the views.py. 

I have added the adfs URLs to the views here:

```
urlpatterns = [
    path('oauth2/', include('django_auth_adfs.urls')),
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('testpage/', views.testpage, name='testpage'),
    path('login/',
         LoginView.as_view
         (
             template_name='app/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Log in',
                 'year' : datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('admin/', admin.site.urls),
]
```

Here are my templates:

```
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
```

And my middleware:

```
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware'
    #'django_auth_adfs.middleware.LoginRequiredMiddleware'
]

ROOT_URLCONF = 'DjangoWebProject1.urls'
```

The login required line was commented out due to it causing errors on launch. 

I also added a template under templates/app/oauth2/callback.html and it does not resolve properly.

Any insight on this is appreciated.

**Comment by JonasKs** [comment]
Hi,
Please turn on debug logging and provide a full stack trace of all the terminal output. 

See [docs](https://django-auth-adfs.readthedocs.io/en/latest/troubleshooting.html#turn-on-django-debug-logging).

**Comment by JonasKs** [comment]
And which version of Django/Django-auth-ADFS are you on? 

You also seem to already have another authentication middleware implemented, have you tried disabling that one?

**Comment by cataclysm1987** [comment]
I have the full stack trace. 

```
Environment:


Request Method: GET
Request URL: http://localhost:59664/oauth2/callback?code=(AZUREADAUTHTOKENREMOVED)
Django Version: 3.2.7
Python Version: 3.9.7
Installed Applications:
['app',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Template loader postmortem
Django tried loading these templates, in this order:

Using engine django:
    * django.template.loaders.app_directories.Loader: C:\Users\conkline\source\repos\DjangoWebProject1\app\templates\django_auth_adfs\login_failed.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: C:\Python39\lib\site-packages\django\contrib\admin\templates\django_auth_adfs\login_failed.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: C:\Python39\lib\site-packages\django\contrib\auth\templates\django_auth_adfs\login_failed.html (Source does not exist)



Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python39\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python39\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Python39\lib\site-packages\django_auth_adfs\views.py", line 66, in get
    return settings.CUSTOM_FAILED_RESPONSE_VIEW(
  File "C:\Python39\lib\site-packages\django_auth_adfs\config.py", line 75, in <lambda>
    self.CUSTOM_FAILED_RESPONSE_VIEW = lambda request, error_message, status: render(
  File "C:\Python39\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Python39\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Python39\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)

Exception Type: TemplateDoesNotExist at /oauth2/callback
Exception Value: django_auth_adfs/login_failed.html

```

I removed the auth token from Azure AD.

**Comment by JonasKs** [comment]
Can you add `django_auth_adfs` to `INSTALLED_APPS`? 

https://django-auth-adfs.readthedocs.io/en/latest/install.html

**Comment by cataclysm1987** [comment]
I did. Now I am receiving a login failed error.

Debug console says authentication backend was called but no authorization code was received.

```
INFO 2021-09-15 08:09:41,998 django_auth_adfs django_auth_adfs loaded settings from ADFS server.
INFO 2021-09-15 08:09:41,998 django_auth_adfs operating mode:         openid_connect
INFO 2021-09-15 08:09:41,998 django_auth_adfs authorization endpoint: https://login.microsoftonline.com/TENANTIDHERE/oauth2/authorize
INFO 2021-09-15 08:09:41,998 django_auth_adfs token endpoint:         https://login.microsoftonline.com/TENANTIDHERE/oauth2/token
INFO 2021-09-15 08:09:41,998 django_auth_adfs end session endpoint:   https://login.microsoftonline.com/TENANTIDHERE/oauth2/logout
INFO 2021-09-15 08:09:41,998 django_auth_adfs issuer:                 https://sts.windows.net/TENANTIDHERE/
[15/Sep/2021 08:09:42] "GET /oauth2/login?next=/ HTTP/1.1" 302 0
DEBUG 2021-09-15 08:09:58,117 django_auth_adfs django_auth_adfs authentication backend was called but no authorization code was received
Unauthorized: /oauth2/callback
[15/Sep/2021 08:09:58] "GET /oauth2/callback?code=(AUTHCODEHERE)
```

**Comment by cataclysm1987** [comment]
Should I create a repository for my code so you guys can see the full source? I am about to give up and just go to .Net Core for this project if I don't get a response soon.

**Comment by JonasKs** [comment]
I don't have the time to really investigate this until next week, but yes, a example repo is a good way to get help. You also have a demo project in this repository [here](https://github.com/snok/django-auth-adfs/blob/master/demo/adfs/mysite/settings.py#L105).

I'd recommend you take a step back and ensure that you have the authentication backends installed, the login required middleware is enabled again, and that your redirect URL from ADFS is correct.  
[Enable debug to get all the logs](https://django-auth-adfs.readthedocs.io/en/latest/troubleshooting.html). 

You've also got a new issue now compared to before, so search the previous issues for similar errors. [This answer](https://github.com/snok/django-auth-adfs/issues/22#issuecomment-342729291) might help you.

**Comment by cataclysm1987** [comment]
You can close out this issue. I was able to resolve it by adding it to the installed apps.

The error afterwards was resolved by updating my reply url to oauth/login. 

Hopefully this helps anyone else.
